#!/bin/sh
# shellcheck disable=SC2164

tomefolder=/media/btrfsv2/containers/data/tomenet

podman run --rm -v "$tomefolder:/srv/build":z registry.tokariew.xyz:5000/tomenet:latest -t iddcmove.patch
[ ! -e "$tomefolder/tomenet-$(date --iso-8601).7z" ] && exit 0
mount /media/dav/
mv "$tomefolder/tomenet-$(date --iso-8601).7z" /media/dav/tomenet/weekly-snapshots ||  curl -d "Kompilator tomeneta się zjebał" -H "X-Tags: warning" https://ntfy.lab.tokariew.xyz/alerts
cd /media/dav/tomenet/weekly-snapshots/
sha256sum "tomenet-$(date --iso-8601).7z" > "tomenet-$(date --iso-8601).7z.sha256sum"
cd ~
echo syncing
rclone sync /media/dav/tomenet/ drop:TomeNET
rclone sync /media/dav/tomenet/ mega:TomeNET
umount /media/dav
