#!/bin/sh

mount /media/dav/
podman start -a tomenet
mv /media/btrfs/containers/tomenet/tomenet-$(date --iso-8601).7z /media/dav/tomenet/weekly-snapshots
cd /media/dav/tomenet/weekly-snapshots/
sha256sum tomenet-$(date --iso-8601).7z > tomenet-$(date --iso-8601).7z.sha256sum
cd ~
echo syncing
rclone sync /media/dav/tomenet/ drop:TomeNET
rclone sync /media/dav/tomenet/ mega:TomeNET
umount /media/dav
